"""Workflow regressions; generated bytes/quality are synthetic, not live acceptance."""
import os
import json
import tempfile
import threading
import unittest
from pathlib import Path
from unittest.mock import patch
from app import pipeline,store,config,review_policy,final_repair,media
from app.production_schema import context_version,file_hash,fingerprint


class PipelineTests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory();self.root=Path(self.tmp.name)
        self.patches=[patch.object(config,'DATA',self.root),patch.object(store,'DATA',self.root),
                      patch.dict(os.environ,{'VIDEO_AGENT_DATABASE_URL':''}),
                      patch.object(pipeline.production,'initialize')]
        for p in self.patches:p.start()
        self.job=store.create({'prompt':'户外跳舞','images':[],'reference':None,'duration':10,'ratio':'9:16',
                               'workflow_version':3,'subject_spec':{'version':'s'},
                               'plan':{'units':[{'id':'u1','duration':10,'description':'小鸡在户外草地连续跳舞','depends_on':[]}],'style':'可爱'}})
        self.project=self.root/'jobs'/self.job['id']/'project';self.project.mkdir(parents=True)
        self.prep=patch.object(pipeline.agent_tools,'prepare',return_value=self.project);self.prep.start()

    def tearDown(self):
        self.prep.stop()
        for p in reversed(self.patches):p.stop()
        self.tmp.cleanup()

    def run_pipeline(self):pipeline.run(store.get(self.job['id']),threading.Event())

    def test_unknown_receipt_never_calls_tools_or_submission(self):
        store.update(self.job['id'],submission_uncertain={'build_id':'unknown'})
        with patch.object(pipeline.agent_tools,'dispatch') as call:
            self.run_pipeline();call.assert_not_called()
        self.assertEqual(store.get(self.job['id'])['status'],'needs_attention')

    def test_invalid_plan_evidence_survives_successful_correction(self):
        proposal={'units':[{'duration':2}]}
        corrected={'units':[{'duration':10}]}
        with patch.object(pipeline.planner,'chat',side_effect=[proposal,corrected]), \
             patch.object(pipeline.agent_tools,'dispatch',side_effect=[ValueError('short film needs one complete unit'),None]) as call:
            pipeline.make_plan(store.get(self.job['id']),self.project,lambda action,args:call(self.job['id'],action,args))
        failures=list((self.project/'production/planning-failures').glob('*.json'))
        self.assertEqual(len(failures),1)
        saved=json.loads(failures[0].read_text())
        self.assertEqual(saved['proposal'],proposal)
        self.assertIn('short film',saved['error'])
        self.assertEqual(call.call_count,2)

    def test_partial_reference_analysis_resumes_without_human_review(self):
        store.update(self.job['id'],reference='long-video',plan=None)
        with patch.object(config,'media_base_url',return_value='https://media.example.com'), \
             patch.object(pipeline.agent_tools,'dispatch',return_value={'status':'in_progress','verified_intervals':2}) as call:
            self.run_pipeline()
            call.assert_called_once_with(self.job['id'],'analyze_reference',{})
        partial=store.get(self.job['id'])
        self.assertEqual(partial['status'],'queued')
        self.assertGreater(partial['next_run_at'],store.now())
        self.assertFalse(partial.get('agent_builds'))

    def test_generation_yields_and_restart_polls_existing_build(self):
        calls=[]
        def dispatch(jid,action,args):
            calls.append(action)
            if action=='generate_unit':
                store.update(jid,agent_builds={'one':{'build_id':'one','unit_id':'u1','state':'pending','generation_seconds':10}})
                return {'state':'pending'}
            raise AssertionError(action)
        with patch.object(pipeline.agent_tools,'dispatch',side_effect=dispatch), \
             patch('app.recovery.hypit.setup',return_value=self.project/'runtime.json'), \
             patch('app.recovery.hypit.status',return_value={'build':{'work':{'state':'running'}}}):
            self.run_pipeline();self.run_pipeline()
        self.assertEqual(calls,['generate_unit'])
        self.assertEqual(store.get(self.job['id'])['status'],'waiting_build')

    def test_insufficient_inspection_cannot_trigger_paid_revision(self):
        clip=self.project/'clip.mp4';clip.write_bytes(b'video');sha=file_hash(clip)
        j=store.get(self.job['id'])
        store.update(j['id'],agent_builds={'one':{'build_id':'one','unit_id':'u1','state':'complete','generation_seconds':10,'collected_sha256':sha}},
                     unit_reviews={'u1':{'verdict':'warn','original_sha256':sha,'context_version':context_version(j),'summary':'音频检查失败'}})
        with patch.object(pipeline.agent_tools,'dispatch') as call:self.run_pipeline();call.assert_not_called()
        self.assertEqual(store.get(j['id'])['status'],'needs_review')

    def test_one_generated_unit_reaches_delivery_without_harness(self):
        clip=self.project/'clip.mp4';clip.write_bytes(b'clip');sha=file_hash(clip);actions=[]
        store.update(self.job['id'],agent_builds={'one':{'build_id':'one','unit_id':'u1','state':'complete','generation_seconds':10,'collected_path':'clip.mp4','collected_sha256':sha}})
        def accepted(j,root,uid):
            r=j.get('unit_reviews',{}).get(uid)
            if not r:raise ValueError('not checked')
            return r
        def dispatch(jid,action,args):
            actions.append(action);j=store.get(jid)
            if action=='collect_review':
                store.update(jid,unit_reviews={'u1':{'verdict':'pass','original_sha256':sha,'context_version':context_version(j)}})
            elif action=='compose_build':
                store.update(jid,agent_builds={**j['agent_builds'],'film':{'build_id':'film','state':'complete','generation_seconds':0}})
                return {'build_id':'film','state':'complete'}
            elif action=='collect':
                (self.project/'output').mkdir();p=self.project/args['to'];p.write_bytes(b'final')
                j['agent_builds']['film'].update(collected_path=args['to'],collected_sha256=file_hash(p))
                store.update(jid,agent_builds=j['agent_builds'])
            elif action=='review':
                store.update(jid,final_review={'verdict':'pass','sha256':file_hash(self.project/args['path']),'context_sha256':context_version(j)})
            elif action=='finish':store.update(jid,status='completed')
            else:raise AssertionError(action)
            return {}
        with patch.object(pipeline.continuity,'accepted',side_effect=accepted),patch.object(pipeline.agent_tools,'dispatch',side_effect=dispatch):self.run_pipeline()
        self.assertEqual(actions,['collect_review','compose_build','collect','review','finish'])
        self.assertEqual(store.get(self.job['id'])['status'],'completed')

    def test_real_audio_track_overrules_no_track_claim_without_granting_pass(self):
        result=review_policy.reconcile({'verdict':'fail','checks':[{'category':'audio','status':'fail','evidence':'全片没有音轨'}]},
                                       [{'audio':{'present':True,'checked':True}}])
        self.assertEqual(result['verdict'],'warn')
        self.assertEqual(result['review_state'],'inspection_incomplete')

    def test_invalid_audio_observation_does_not_authorize_regeneration(self):
        result=review_policy.reconcile({'verdict':'fail','checks':[]},[{'audio':{'present':True,'checked':False}}])
        self.assertEqual(result['verdict'],'warn')

    def test_unlocatable_final_failure_cannot_regenerate_all_units(self):
        j=store.get(self.job['id'])
        self.assertEqual(final_repair.targets(j,{'checks':[{'status':'fail','evidence':'looks wrong'}]}),[])
        self.assertEqual(final_repair.targets(j,{'checks':[{'status':'fail','unit_ids':['u1']}]}),['u1'])
        self.assertEqual(final_repair.targets(j,{'checks':[{'status':'fail','unit_ids':['invented']}]}),[])

    def test_final_failure_requires_unit_evidence_then_repairs_only_once(self):
        p=self.project/'clip.mp4';p.write_bytes(b'clip');sha=file_hash(p)
        j=store.get(self.job['id']);ctx=context_version(j)
        accepted={'version':'v1','verdict':'pass','path':'clip.mp4','sha256':sha,'original_sha256':sha,'context_version':ctx}
        render={'build_id':'film','state':'complete','generation_seconds':0,'collected_path':'clip.mp4','collected_sha256':sha}
        store.update(j['id'],unit_reviews={'u1':accepted},agent_builds={'one':{'build_id':'one','unit_id':'u1','state':'complete','generation_seconds':10,'collected_path':'clip.mp4','collected_sha256':sha},'film':render},
                     pipeline_render_key=fingerprint([['clip.mp4',sha,'v1']]),pipeline_render_id='film',
                     final_review={'verdict':'fail','sha256':sha,'context_sha256':ctx,'checks':[{'status':'fail','unit_ids':['u1'],'evidence':'缺少舞蹈动作'}]})
        actions=[]
        def accepted_unit(job,root,uid):
            r=job['unit_reviews'][uid]
            if r['verdict']!='pass':raise ValueError('failed')
            return r
        def dispatch(jid,action,args):
            actions.append(action);job=store.get(jid)
            if action=='review_unit':
                self.assertTrue(args['final_recheck'])
                r={**accepted,'verdict':'fail','checks':[{'status':'fail','evidence':'实际只有轻微晃动'}]}
                store.update(jid,unit_reviews={'u1':r});return r
            if action=='generate_unit':
                store.update(jid,agent_builds={**job['agent_builds'],'two':{'build_id':'two','unit_id':'u1','state':'pending','generation_seconds':10}})
                return {'state':'pending'}
            raise AssertionError(action)
        def waiting(job,stop,once):
            if any(b['state']=='pending' for b in job.get('agent_builds',{}).values()):
                store.update(job['id'],status='waiting_build');raise pipeline.WorkDeferred()
            return False
        with patch.object(pipeline.continuity,'accepted',side_effect=accepted_unit),patch.object(pipeline.agent_tools,'dispatch',side_effect=dispatch),patch.object(pipeline,'wait_builds',side_effect=waiting):
            self.run_pipeline();self.run_pipeline()
        self.assertEqual(actions,['review_unit','generate_unit'])
        self.assertEqual(store.get(j['id'])['status'],'waiting_build')

    def test_pcm_measurement_distinguishes_silence_from_existing_audio(self):
        import wave
        for sample,silent in [(b'\0\0',True),(b'\0\x10',False)]:
            path=self.root/'audio.wav'
            with wave.open(str(path),'wb') as out:
                out.setnchannels(1);out.setsampwidth(2);out.setframerate(16000);out.writeframes(sample*16000)
            metrics=media.audio_metrics(path)
            self.assertEqual(metrics['near_silent'],silent)
